### ISSUE TITLE
Register this project for Mozilla Science Lab Global Sprint 2016 

### ISSUE THREAD

**Issue by konrad** [OKScienceDE/Open_Science_101#10]
More detail on the [even page](https://www.mozillascience.org/global-sprint-2016).

**Comment by konrad** [comment]
https://github.com/mozillascience/global-sprint-2016/issues/36

We just need "least one person will be available to review and answer questions on this project from 9-5 in their timezone on both June 2 & 3." Any volunteers?

**Comment by aleimba** [comment]
It would also be great, if the project would be featured on the Mozilla Global sprint website. For this we would need to complete the checklist in the issue (https://github.com/mozillascience/global-sprint-2016/issues/36) with README, LICENSE, Roadmap etc. for the sprint and then contact @acabunoc.

**Comment by aleimba** [comment]
We've completed the checklist and have submitted the project for review: mozillascience/global-sprint-2016#36

**Comment by aleimba** [comment]
Hooray, we're a registered project now: https://science.mozilla.org/projects/open-science-101
