### ISSUE TITLE
Define aim/deliverable for Mozilla Science Lab Global Sprint 2016 

### ISSUE THREAD

**Issue by konrad** [OKScienceDE/Open_Science_101#23]
What doe we want to do at the Mozilla Science Lab Global Sprint 2016 (#10) and what do we want to have after it?

**Comment by aleimba** [comment]
As @konrad suggested, we should focus on a few subjects at first and create high quality content for these at first.

Finishing the checklist to become a Mozilla Global Sprint project would also help to streamline the project for the sprint and define a timeline, see issue #10. Useful are also the Mozilla Science Lab resources for "Working Open Workshop" (https://mozillascience.github.io/working-open-workshop/).

**Comment by konrad** [comment]
Also add text to milestone description

**Comment by matthiasfromm** [comment]
Added some particular goals for the sprint within the descriptio (reflecting the issues collected within the milestone).
