### ISSUE TITLE
Define common structure for each topic

### ISSUE THREAD

**Issue by konrad** [OKScienceDE/Open_Science_101#25]
We should have a consistent way of presenting the different topics. E.g. each if we assume handout format each topic could have a section like "2 min abstract "Problem/Current status", "Solution", "Further Reading". Also the length should be harmonize between the different documents.

**Comment by matthiasfromm** [comment]
What we should also think about is the format the teaching material itself will be provided.

I would strongly suggest to handle it similarly to the Software/Data Carpentry and use HTML/Markdown to provide e.g. Github pages for each topic.

If I remember correctly, the Open Science Training Initiative provided their main lessons as .docx, .pptx or .odp files which makes it harder for others to contribute, but also harder to maintain.

However, providing .ZIPs or PDFs for local use of lessons (PDF generated by pandoc?) could be also helpful.

As an enhancement for later stages one could offer an introductional video for each topic...but that is quite far away I think. ;-)

**Comment by aleimba** [comment]
yep, agree. Is also related to #20 and #27.

Markdown has the lowest entry point I think, easy to learn and maintain with the additional advantage of easy conversion to other formats like HTML. PDFs can also be generated with `pandoc` if needed, a small makefile could be provided in each topic repository and the PDFs automatically regenerated with each commit via a git hook.

For a short discussion on the advantages and disadvantages of video material see #22.

**Comment by konrad** [comment]
Agree - build on Markdown and create conversion pipelines

**Comment by konrad** [comment]
Done. See Topic_Template.md
