### ISSUE TITLE
Generate Personas file

### ISSUE THREAD

**Issue by konrad** [OKScienceDE/Open_Science_101#32]

**Comment by konrad** [comment]
See https://mozillascience.github.io/working-open-workshop/personas_pathways/

**Comment by matthiasfromm** [comment]
Was just reading up a bit on personas. Something like seems to be quite useful in my view: https://github.com/joyent/sdc-docker/blob/master/docs/development/use-case-personas.md

If you need support @konrad, let us know! No prob!

**Comment by konrad** [comment]
Nice, thank! I drafted a file for now and will continue tomorrow. Feel free to extend/change/ it!
