### ISSUE TITLE
Generate Code of Conduct

### ISSUE THREAD

**Issue by konrad** [OKScienceDE/Open_Science_101#33]

**Comment by matthiasfromm** [comment]
This one is a good starting point I think: https://github.com/WorldBrain/START-HERE/blob/master/CODE_OF_CONDUCT.md

**Comment by konrad** [comment]
Seee https://mozillascience.github.io/working-open-workshop/personas_pathways/

**Comment by konrad** [comment]
See https://mozillascience.github.io/working-open-workshop/contributing/

**Comment by konrad** [comment]
See https://mozillascience.github.io/working-open-workshop/code_of_conduct/

**Comment by matthiasfromm** [comment]
Generated CODE_OF_CONDUCT.md so that I could add the link to it from Contributing.md

**Comment by aleimba** [comment]
The WorldBrain CoD sadly is CC-BY-SA, thus I couldn't just copy/paste with some minor edits (all our material should be CC0). However, found the Chromium CC0 CoD (https://www.chromium.org/conduct), which I used mostly and supplemented with some own stuff and some from WorldBrain.
