### ISSUE TITLE
Generate CONTRIBUTING.md

### ISSUE THREAD

**Issue by konrad** [OKScienceDE/Open_Science_101#34]

**Comment by konrad** [comment]
See https://github.com/mozillascience/global-sprint-2016/issues/36

**Comment by konrad** [comment]
See https://mozillascience.github.io/working-open-workshop/code_of_conduct/

**Comment by konrad** [comment]
See https://mozillascience.github.io/working-open-workshop/contributing/

**Comment by matthiasfromm** [comment]
Added basic text to contributing.md.
