### ISSUE TITLE
Refine target group

### ISSUE THREAD

**Issue by matthiasfromm** [OKScienceDE/Open_Science_101#36]
With an open science training there are possibly different target groups that have different interests in open science and thus require different scopes and/or motivation (undergraduate students, PhD's, senior researchers all have their own view). It might be worth thinking about defining the "relevant" target groups and make material available that caters the different needs (maybe also in recombination of various material).

This issue is closely related to #4.

This issue has formerly been part of #6.

This issue takes up the personas designed for the Mozilla Sprint.

**Comment by konrad** [comment]
This has been started in the PERSONAS.md file which should be further improved. See #39
