### ISSUE TITLE
Similar project: Open Science Training Initiative

### ISSUE THREAD

**Issue by jcmolloy** [OKScienceDE/Open_Science_101#40]
https://github.com/StilettoFiend/OpenScienceTraining

**Comment by matthiasfromm** [comment]
Thanks Jenny!

We have the OSTI [already on our radar](https://openscience.uni-bielefeld.de/898/which-materials-exist-introducing-specific-audiences-science?show=900#a900) and are even already in contact with Sophie Kay.

Nevertheless, thanks for contributing!

**Comment by jcmolloy** [comment]
Hi Matthias
Great! Good to know (sorry I hadn't checked thoroughly enough!)

Jenny

**Comment by matthiasfromm** [comment]
Don't worry, we're happy about any note. ;-)

**Comment by matthiasfromm** [comment]
Closely related to #5 and included in the [material collection](https://openscience.uni-bielefeld.de/898/which-materials-exist-introducing-specific-audiences-science).

Closing this issue to avoid duplicates, if okay.
