### ISSUE TITLE
Check out what's already there

### ISSUE THREAD

**Issue by Daniel-Mietchen** [OKScienceDE/Open_Science_101#5]
Lots of things have been written or otherwise produced about open science already.

We should attempt to get an overview of that landscape, so that we can make conscious decisions as to whether to link to/ ignore/ incorporate/ (re)start some specific materials.

If you know such materials, please post them over at [Open Science Q&A](https://openscience.uni-bielefeld.de/898/which-materials-exist-introducing-specific-audiences-science), so that this ticket can concentrate on what to incorporate into this 101.

**Comment by merriam** [comment]
Hmmm....   I respectfully disagree.   While a forum based Q&A is an easy way for people to add hints, a curated list is useful.   Oddly, the most valuable place to write an overview is to update the Wikipedia page:  https://en.wikipedia.org/wiki/Open_science.   That forum has a wide audience, mature editing tools, dispute resolution, and high SEO.

**Comment by merriam** [comment]
I added a simple Resources.MD list as an example (https://github.com/OKScienceDE/Open_Science_101/pull/7).   Would it be better to push these lists into some sort of Wikipedia framework?  Open science is to large for a central, curated list of resources but still small enough for a crowdsourced list.

**Comment by Daniel-Mietchen** [comment]
Agreed on the usefulness of a curated list like your Resources.md. Of course we can do the entire project here on GitHub, but since we have the Q & A site for things like this, we might as well use it. 

As for doing this a Wikimedia context, we could easily have the list as part of the Open science article, on a Wikiversity page or possibly in a dedicated Wikipedia list article, but in these cases, the content would be licensed CC BY-SA, whereas we are going for CC0 here to maximize reuse, including on Wikimedia projects.

**Comment by merriam** [comment]
I see your point, though a philosophical discussion on the merits or "attribution-required" versus "public domain" would be an enjoyable evening.   I have started updating the Wikipedia pages.

**Comment by merriam** [comment]
I finished the first pass on https://en.wikipedia.org/wiki/Open_science#Organizations_and_projects_of_open_science.  The next item would be to expand it with a section of what materails are already available.

What would be a good tool to run a crowdsourced and curated list of open science projects and materials?

**Comment by merriam** [comment]
OK; added resources and linky to wikipedia for about half of Resources.txt and made a PR for reorg.

Really need a database.   Will open an issue.

**Comment by merriam** [comment]
FYI; finished a pass on Wikipedia's Open Science article a few days ago.  That is, all the random links in the article were organized into prose.

**Comment by konrad** [comment]
We will add the link to the Q&A into the README.md
