### ISSUE TITLE
Define target group(s) and find a categorizaion system to match resources

### ISSUE THREAD

**Issue by matthiasfromm** [OKScienceDE/Open_Science_101#6]
With an open science training there are possibly different target groups that have different interests in open science and thus require different scopes and/or motivation (undergraduate students, PhD's, senior researchers all have their own view). It might be worth thinking about defining the "relevant" target groups and make material available that caters the different needs (maybe also in recombination of various material).

This issue is closely related to #4.

Furthermore it might be helpful to work on a categorization system to mark which material is reasonable for which target group. This could be done by tags, icons or badges - similar to the idea behind [Open Badges](http://openbadges.org/), or the badge system that the Association for Psychological Science has implemented with the [Open Practices](https://www.psychologicalscience.org/index.php/publications/journals/psychological_science/badges).

**Comment by aleimba** [comment]
I think we all agree that our main target will be university-associated folks. However, I think the motivation/troubles of different "career stages" at the university are very overlapping. Nevertheless, a badge system is useful.

But, I see bigger differences for different scientific fields. E.g. life scientists will have a big focus on open data (with big data issues), whereas social scientists might be more interested in publishing open and collaborative books etc.

**Comment by matthiasfromm** [comment]
Absolutely right @aleimba! I think with a clever badge system we could look into using both elements of the badge (the icon and the colour) to indicate different things e.g. the discipline and the "level" or target group or "type of content".

**Comment by matthiasfromm** [comment]
Closing this issue since it is divided into 2 individual ones - #36 and #37.
